// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-trades.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trades_default = defineTool({
  name: "list_trades",
  title: "Listar negocia\xE7\xF5es",
  description: "Lista as negocia\xE7\xF5es do utilizador autenticado, opcionalmente filtradas por mercado (forex, crypto, propfirm) e/ou estado (open, closed).",
  inputSchema: {
    market: z.enum(["forex", "crypto", "propfirm"]).optional(),
    status: z.enum(["open", "closed"]).optional(),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ market, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("trades").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (market) q = q.eq("market", market);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-trade.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_trade_default = defineTool2({
  name: "create_trade",
  title: "Criar negocia\xE7\xE3o",
  description: "Cria uma nova negocia\xE7\xE3o para o utilizador autenticado. O mercado deve ser forex, crypto ou propfirm.",
  inputSchema: {
    market: z2.enum(["forex", "crypto", "propfirm"]),
    pair: z2.string().min(1),
    direction: z2.enum(["long", "short"]),
    entry_price: z2.number(),
    stop_loss: z2.number(),
    take_profit: z2.number(),
    position_size: z2.number(),
    risk_amount: z2.number(),
    risk_percentage: z2.number(),
    risk_reward_ratio: z2.number(),
    potential_profit: z2.number(),
    notes: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("trades").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trade: data }
    };
  }
});

// src/lib/mcp/tools/list-analyses.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_analyses_default = defineTool3({
  name: "list_analyses",
  title: "Listar an\xE1lises (win/loss)",
  description: "Lista as an\xE1lises (Acertos e Erros) do utilizador autenticado, opcionalmente filtradas por mercado e tipo.",
  inputSchema: {
    market: z3.enum(["forex", "crypto", "propfirm"]).optional(),
    type: z3.enum(["win", "loss"]).optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ market, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("trade_analyses").select("id,market,type,asset_pair,amount,risk_reward,risk_percentage,notes,created_at,setup_id").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (market) q = q.eq("market", market);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { analyses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-setups.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_setups_default = defineTool4({
  name: "list_setups",
  title: "Listar setups do playbook",
  description: "Lista os setups do playbook do utilizador autenticado, opcionalmente filtrados por mercado.",
  inputSchema: {
    market: z4.enum(["forex", "crypto", "propfirm"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ market }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("trade_setups").select("*").order("created_at", { ascending: false });
    if (market) q = q.eq("market", market);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { setups: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-balances.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_balances_default = defineTool5({
  name: "get_balances",
  title: "Obter saldos das contas",
  description: "Retorna os saldos actuais das contas Forex, Cripto e PropFirm do utilizador autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const [{ data: risk }, { data: prop }] = await Promise.all([
      sb.from("risk_settings").select("account_balance,crypto_account_balance").maybeSingle(),
      sb.from("propfirm_settings").select("name,funded_balance,profit_target,max_drawdown,daily_drawdown").maybeSingle()
    ]);
    const balances = {
      forex: risk?.account_balance ?? 0,
      crypto: risk?.crypto_account_balance ?? 0,
      propfirm: {
        name: prop?.name ?? null,
        balance: prop?.funded_balance ?? 0,
        profit_target: prop?.profit_target ?? 0,
        max_drawdown: prop?.max_drawdown ?? 0,
        daily_drawdown: prop?.daily_drawdown ?? 0
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(balances) }],
      structuredContent: balances
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "abhojfnyeqgolsgphvhl";
var mcp_default = defineMcp({
  name: "c-risco-mcp",
  title: "C-RISCO \u2014 Gest\xE3o de Trades",
  version: "0.1.0",
  instructions: "Ferramentas para gerir o di\xE1rio de trading C-RISCO do utilizador: listar/criar negocia\xE7\xF5es, consultar saldos (Forex, Cripto, PropFirm), listar an\xE1lises (Acertos/Erros) e setups do playbook. Todos os dados s\xE3o isolados por utilizador via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trades_default, create_trade_default, list_analyses_default, list_setups_default, get_balances_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
